[web]
enabled = true
host = ":8080"

# [web.cors]
# enabled = true
#
# [web.pprof]
# enabled = true
#
# [sql.default]
# enabled = true
# driver = "sqlite3"
# dsn = ":memory:"
#
# [sql.asoy]
# enabled = true
# driver = "sqlite3"
# dsn = ":memory:"
#
