net:
  enabled: true
  type: tcp
  address: :8080

web:
  enabled: true
  host: :8081
  cors:
    enabled: true
    allow_origins: '*'
  pprof:
    enabled: true

grpc:
  enabled: true
  host: :8082

sql:
  default:
    enabled: true
    driver: sqlite3
    dsn: ":memory:"

  master:
    enabled: false
    driver: postgres
    dsn: $SQL_DSN

  transactions:
    enabled: false
    driver: postgres
    dsn: $SQL_DSN 

others:
  key: $VALUE
